### PR TITLE
Create app.properties for Italian translation

### PR DESCRIPTION
**Pull request by Airon90**
Create app.properties for Italian translation

### CODE REVIEW

**Comment by freaktechnik** [comment]
Do you intend on translating it further? Will you do that on transifex or via pull request?

**Comment by Airon90** [comment]
I accidentally made the PR while translating. I'm finishing translating right now here :)

**Comment by Airon90** [comment]
I have to translate 3 remaining keys. Please give me some minutes ^^

**Comment by Airon90** [comment]
Please, could you send me a link to the Transifex page, so that I can translate the app into Esperanto? Thank you!

**Comment by freaktechnik** [comment]
Okay, cool! And thank you for the translation!

**Comment by freaktechnik** [comment]
I assume you found the transifex page? In any case: https://www.transifex.com/projects/p/mines/

**Comment by freaktechnik** [comment]
Oh, and whenever the travis CI build is through (so a short time after a commit landed in this repo), the translation will be live on http://lab.humanoids.be/mines.js, so you can test it.

**Comment by Airon90** [comment]
Yes! I saw it on the README file :)

**Pull request merged**
